---
version: '2.2'

services:
  rhubarb-recipes-service:
    build:
      context: .
    cpus: 2.5
    mem_limit: 1024M
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: toffee
      POSTGRES_USER: toffee
      POSTGRES_PASSWORD: toffee
      POSTGRES_SSL_MODE: disable
      AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY:
      JAVA_OPTS:
    ports:
      - 9080:4550
  postgres:
   image: postgres:11-alpine
   environment:
     POSTGRES_USER: toffee
     POSTGRES_PASSWORD: toffee
     POSTGRES_DB: toffee
   ports:
     - 5460:5432
