java:
  applicationPort: 4550
  aadIdentityName: toffee
  readinessPath: '/health/readiness'
  # Don't modify below here
  image: 'sdshmctspublic.azurecr.io/toffee/recipe-backend:latest'
  environment:
    POSTGRES_SSL_MODE: require
  keyVaults:
    "toffeesi":
      secrets:
        - name: recipe-backend-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: recipe-backend-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: recipe-backend-POSTGRES-USER
          alias: POSTGRES_USER
        - name: recipe-backend-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
