java:
  applicationPort: 4550
  aadIdentityName: toffee
  readinessPath: '/health/readiness'
  # Don't modify below here
  image: 'sdshmctspublic.azurecr.io/toffee/recipe-backend:latest'
  environment:
    POSTGRES_SSL_MODE: require
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: /mnt/secrets/toffeesi/app-insights-config
  keyVaults:
    "toffeesi":
      secrets:
        - name: recipe-backend-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: recipe-backend-POSTGRES-HOST-v14
          alias: POSTGRES_HOST
        - name: recipe-backend-POSTGRES-USER-v14
          alias: POSTGRES_USER
        - name: recipe-backend-POSTGRES-PASS-v14
          alias: POSTGRES_PASSWORD
        - name: recipe-backend-app-insights-config
          alias: app-insights-config
